import React from 'react';
import {Link} from 'react-router';

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

class Problem2 extends React.Component{
  constructor(props, context) {
    super(props, context);
  }

  getSumOfEvenValuedFibonnaciBelow(limit){
    let sum = 2;
    let num1 = 1;
    let num2 = 2;
    let num3 = num1 + num2;
    
    if(limit <= 1){
      return 0;
    }
    
    if(limit <=3){
      return 2;
    }
    
    while (num3 < limit){
      num1 = num2;
      num2 = num3;
      num3 = num1 + num2;
      
      if(num3%2 == 0){
        sum+= num3;
      }
    }
    
    return sum;
    
  }

  render(){
    return (
      <div>
        <h1>Even Fibonacci numbers</h1>
        <h4>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</h4>
        <h4>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</h4>
        <h4>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</h4>
        <p>Answer: {this.getSumOfEvenValuedFibonnaciBelow(4000000)} </p>
      </div>
    );
  }
}

export default Problem2;
